// Generated by CoffeeScript 1.8.0
(function() {
  var StudioAssetRemoteFileUploader;

  StudioAssetRemoteFileUploader = (function() {
    function StudioAssetRemoteFileUploader(options) {
      this.assetServiceLink = this.options.assetServiceLink;
    }

    StudioAssetRemoteFileUploader.prototype.uploadFile = function(fileUrl) {
      this.assetServiceLink.payload.fileUrl = fileUrl;
      return $.ajax({
        url: this.assetServiceLink.href,
        async: false,
        method: 'POST',
        data: this.assetServiceLink.payload,
        success: (function(_this) {
          return function(data, status, xhr) {
            return console.log("DONE", data);
          };
        })(this)
      });
    };

    return StudioAssetRemoteFileUploader;

  })();

}).call(this);
